### ISSUE TITLE
Generating passwords exits abnormally

### ISSUE THREAD

**Issue by cmacrae** [ecraven/ivy-pass#3]
Hey @ecraven 👋 

Thanks for this awesome little package - I use it every day!  
Recently, I noticed that when generating new passwords, the following message is returned in a buffer:
```
EDITOR=sh\ -c\ \'echo\ \"WITH-EDITOR\:\ \$\$\ OPEN\ \$0\"\;\ sleep\ 604800\ \&\ sleep\=\$\!\;\ trap\ \"kill\ \$sleep\;\ exit\ 0\"\ USR1\;\ trap\ \"kill\ \$sleep\;\ exit\ 1\"\ USR2\;\ wait\ \$sleep\' /run/current-system/sw/bin/pass edit Some/Password: exited abnormally with code 1.
```
It still generates the password fine.

This didn't used to happen. Any ideas what's going on?

**Comment by ecraven** [comment]
Thanks. I can reproduce this, it is a bug in password-store.el (or even deeper), `with-editor-async-shell-command` fails... I'll try to get them to fix it upstream, if that doesn't work, I'll implement a workaround.

**Comment by cmacrae** [comment]
Awesome, thanks!

**Comment by ecraven** [comment]
Upstream is tracked here: https://github.com/magit/with-editor/issues/40

**Comment by ecraven** [comment]
Seems this is fixed upstream: https://github.com/magit/with-editor/commit/73d3d1ac1470001e184a5ead88f770eeb71a5461

**Comment by cmacrae** [comment]
Yep, looks like password generation now works @ecraven, however I'm now presented with another issue:  

When generating a password from `ivy-pass`, I'm prompted for the name of the password.  
I enter it, hit Return, and a new buffer is displayed with the following contents:  
```
^X Exit                       ^J Justify                    ^W Where Is                   ^V Next Page                  ^U UnCut Text                 ^T To Spell
```
Which looks like `nano`...  

The same thing is observed when trying to edit any entries.  

Is it possible that the shell command being run here is somehow picking up `nano` as my `EDITOR`? My `EDITOR` env var is set to `emacsclient` in my shell.

**Comment by ecraven** [comment]
Do you still see this issue? I just updated everything again today and added a new entry, seems to work fine.
